version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: netfarm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: netfarm
      POSTGRES_CONNECTION_STRING: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable"
      BUCKET_NAME: document-land
      FILE_CONFIG_GOOGLE_STORAGE: keys.json
      BASE_URL_GOOGLE_STORAGE: https://storage.googleapis.com
    volumes:
      - .:/app

volumes:
  db-data:
