AWSTemplateFormatVersion: '2010-09-09'

Description: ACD Plataform Secrets

Parameters:

  ProjectName:
    Type: String
    Default: netfarm

Resources:

  DatabaseUrlSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/DATABASE_URL'
      Description: Database connection string
      SecretString: '{}'

  BucketNameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/BUCKET_NAME'
      Description: Google Cloud Storage bucket name
      SecretString: '{}'

  FileConfigGoogleStorageSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/FILE_CONFIG_GOOGLE_STORAGE'
      Description: Google Cloud Storage configuration file
      SecretString: '{}'

  BaseUrlGoogleStorageSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/BASE_URL_GOOGLE_STORAGE'
      Description: Google Cloud Storage base URL
      SecretString: '{}'

  PortSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/PORTPORT'
      Description: Application port
      SecretString: '{}'

Outputs:

  DatabaseUrlSecretArn:
    Value: !Ref DatabaseUrlSecret
    Export:
      Name: !Sub '${ProjectName}-DatabaseUrlSecretArn'

  BucketNameSecretArn:
    Value: !Ref BucketNameSecret
    Export:
      Name: !Sub '${ProjectName}-BucketNameSecretArn'

  FileConfigGoogleStorageSecretArn:
    Value: !Ref FileConfigGoogleStorageSecret
    Export:
      Name: !Sub '${ProjectName}-FileConfigGoogleStorageSecretArn'

  BaseUrlGoogleStorageSecretArn:
    Value: !Ref BaseUrlGoogleStorageSecret
    Export:
      Name: !Sub '${ProjectName}-BaseUrlGoogleStorageSecretArn'

  PortSecretArn:
    Value: !Ref PortSecret
    Export:
      Name: !Sub '${ProjectName}-PortSecretArn'